#!/bin/sh
set -eu

BASE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
RESULT_LABEL=RENDER_ENV
. "$BASE_DIR/common.sh"

MODE=''
CONFIG=/etc/akamai-mfa/production.conf

while [ "$#" -gt 0 ]; do
    case "$1" in
        --check-only) MODE=check ;;
        --apply) MODE=apply ;;
        --config)
            shift
            [ "$#" -gt 0 ] || fail missing_config_argument
            CONFIG=$1
            ;;
        -h|--help)
            echo "usage: $0 (--check-only|--apply) [--config FILE]"
            exit 0
            ;;
        *) fail "unknown_argument_$1" ;;
    esac
    shift
done

[ -n "$MODE" ] || fail mode_required
require_root
for cmd in grep cut stat install mktemp cmp; do
    require_cmd "$cmd"
done
require_protected_file "$CONFIG"

allowed_key() {
    case "$1" in
        EXPECTED_REPO_COMMIT|POSTGRES_USER|PGDATA|POSTGRES_DB|\
        AKAMAI_HOST|AKAMAI_CONTRACT_ID|AKAMAI_DIRECTORY_ID|AKAMAI_CONNECT_TIMEOUT|AKAMAI_READ_TIMEOUT|LOG_LEVEL|\
        OPERATION_TTL_SECONDS|OPERATION_EXECUTION_TIMEOUT_SECONDS|OPERATION_RETENTION_SECONDS|NO_PROXY|\
        SIMULATION_PRIMITIVE_OUTCOME|SIMULATION_POSTCHECK_OUTCOME|\
        MFA_API_URL|MFA_API_TIMEOUT|MCP_HOST|MCP_PORT|MCP_LOG_LEVEL|\
        MCP_TRUSTED_INGRESS_MODE|MCP_TRUSTED_INGRESS_HEADER_NAME|MCP_TRUSTED_CONTEXT_MODE|\
        MCP_ACTOR_HEADER_NAME|MCP_SESSION_HEADER_NAME|MCP_INTERACTION_ATTESTATION_MODE|\
        MCP_INTERACTION_HEADER_NAME|MCP_LOG_ATTESTATION_PROBE) return 0 ;;
        *) return 1 ;;
    esac
}

while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
        ''|'#'*) continue ;;
    esac
    case "$line" in
        *=*) ;;
        *) fail config_line_without_equals ;;
    esac
    key=${line%%=*}
    case "$key" in
        ''|*[!A-Z0-9_]*) fail "invalid_config_key_$key" ;;
    esac
    allowed_key "$key" || fail "unknown_config_key_$key"
done < "$CONFIG"

REQUIRED_KEYS='EXPECTED_REPO_COMMIT POSTGRES_USER PGDATA POSTGRES_DB AKAMAI_HOST AKAMAI_CONTRACT_ID AKAMAI_DIRECTORY_ID AKAMAI_CONNECT_TIMEOUT AKAMAI_READ_TIMEOUT LOG_LEVEL OPERATION_TTL_SECONDS OPERATION_EXECUTION_TIMEOUT_SECONDS OPERATION_RETENTION_SECONDS NO_PROXY SIMULATION_PRIMITIVE_OUTCOME SIMULATION_POSTCHECK_OUTCOME MFA_API_URL MFA_API_TIMEOUT MCP_HOST MCP_PORT MCP_LOG_LEVEL MCP_TRUSTED_INGRESS_MODE MCP_TRUSTED_INGRESS_HEADER_NAME MCP_TRUSTED_CONTEXT_MODE MCP_ACTOR_HEADER_NAME MCP_SESSION_HEADER_NAME MCP_INTERACTION_ATTESTATION_MODE MCP_INTERACTION_HEADER_NAME MCP_LOG_ATTESTATION_PROBE'

for key in $REQUIRED_KEYS; do
    get_config_value "$CONFIG" "$key" >/dev/null
done

echo "CONFIG_VALIDATION=PASS"

[ "$MODE" = apply ] || {
    echo "RENDER_ENV=CHECK_PASS"
    exit 0
}

CONFIG_ROOT=/opt/akamai-mfa/config
for d in "$CONFIG_ROOT/postgres-v2" "$CONFIG_ROOT/api-v2" "$CONFIG_ROOT/mcp-v2"; do
    [ -d "$d" ] || fail "missing_config_directory_$d"
done

TMP_DIR=$(mktemp -d /tmp/akamai-mfa-env.XXXXXX)
trap 'rm -rf "$TMP_DIR"' EXIT HUP INT TERM
umask 077

{
    echo '# Generated by deploy/production/automation/render-env.sh'
    printf 'POSTGRES_USER=%s\n' "$(get_config_value "$CONFIG" POSTGRES_USER)"
    echo 'POSTGRES_PASSWORD_FILE=/run/secrets/pg_password'
    printf 'PGDATA=%s\n' "$(get_config_value "$CONFIG" PGDATA)"
    printf 'POSTGRES_DB=%s\n' "$(get_config_value "$CONFIG" POSTGRES_DB)"
} > "$TMP_DIR/postgres-v2.env"

{
    echo '# Generated by deploy/production/automation/render-env.sh'
    for key in AKAMAI_HOST AKAMAI_CONTRACT_ID AKAMAI_DIRECTORY_ID AKAMAI_CONNECT_TIMEOUT AKAMAI_READ_TIMEOUT LOG_LEVEL OPERATION_TTL_SECONDS OPERATION_EXECUTION_TIMEOUT_SECONDS OPERATION_RETENTION_SECONDS NO_PROXY; do
        printf '%s=%s\n' "$key" "$(get_config_value "$CONFIG" "$key")"
    done
    echo 'EXECUTION_BACKEND=simulation'
    printf 'SIMULATION_PRIMITIVE_OUTCOME=%s\n' "$(get_config_value "$CONFIG" SIMULATION_PRIMITIVE_OUTCOME)"
    printf 'SIMULATION_POSTCHECK_OUTCOME=%s\n' "$(get_config_value "$CONFIG" SIMULATION_POSTCHECK_OUTCOME)"
} > "$TMP_DIR/api-v2.env"

{
    echo '# Generated by deploy/production/automation/render-env.sh'
    for key in MFA_API_URL MFA_API_TIMEOUT MCP_HOST MCP_PORT MCP_LOG_LEVEL MCP_TRUSTED_INGRESS_MODE MCP_TRUSTED_INGRESS_HEADER_NAME; do
        printf '%s=%s\n' "$key" "$(get_config_value "$CONFIG" "$key")"
    done
    echo 'MCP_TRUSTED_INGRESS_SECRET_FILE=/run/secrets/akamai-mfa-mcp-ingress-token'
    for key in MCP_TRUSTED_CONTEXT_MODE MCP_ACTOR_HEADER_NAME MCP_SESSION_HEADER_NAME MCP_INTERACTION_ATTESTATION_MODE MCP_INTERACTION_HEADER_NAME MCP_LOG_ATTESTATION_PROBE; do
        printf '%s=%s\n' "$key" "$(get_config_value "$CONFIG" "$key")"
    done
    echo 'MCP_DESTRUCTIVE_EXECUTION_MODE=disabled'
} > "$TMP_DIR/mcp-v2.env"

POSTGRES_DST="$CONFIG_ROOT/postgres-v2/postgres-v2.env"
API_DST="$CONFIG_ROOT/api-v2/api-v2.env"
MCP_DST="$CONFIG_ROOT/mcp-v2/mcp-v2.env"

# Validate every destination before installing any generated env file.
precheck_env() {
    src=$1
    dst=$2
    if [ -e "$dst" ] && ! cmp -s "$src" "$dst"; then
        fail "existing_live_env_differs_$dst"
    fi
}
precheck_env "$TMP_DIR/postgres-v2.env" "$POSTGRES_DST"
precheck_env "$TMP_DIR/api-v2.env" "$API_DST"
precheck_env "$TMP_DIR/mcp-v2.env" "$MCP_DST"

install_env() {
    src=$1
    dst=$2
    if [ -e "$dst" ]; then
        echo "ENV_UNCHANGED=$dst"
        return 0
    fi
    install -o root -g root -m 0640 "$src" "$dst"
    echo "ENV_INSTALLED=$dst"
}

install_env "$TMP_DIR/postgres-v2.env" "$POSTGRES_DST"
install_env "$TMP_DIR/api-v2.env" "$API_DST"
install_env "$TMP_DIR/mcp-v2.env" "$MCP_DST"

echo "RENDER_ENV=PASS"
